import django.contrib.contenttypes.fields
import django.contrib.contenttypes.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0004_user_can_access_legal_compliance_module_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAPA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("capa_number", models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source_type", models.CharField(choices=[("INCIDENT", "Incident"), ("HAZARD", "Hazard"), ("INSPECTION", "Inspection"), ("AUDIT", "Audit"), ("OBSERVATION", "Observation"), ("RISK_ASSESSMENT", "Risk Assessment"), ("LEGAL_COMPLIANCE", "Legal Compliance"), ("MANAGEMENT_REVIEW", "Management Review"), ("MANUAL", "Manual")], default="MANUAL", max_length=30)),
                ("source_object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("severity", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], default="MEDIUM", max_length=20)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("URGENT", "Urgent")], default="MEDIUM", max_length=20)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("reason_required", models.TextField(blank=True)),
                ("capa_recommended", models.BooleanField(default=False)),
                ("capa_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("OPEN", "Open"), ("INVESTIGATION_IN_PROGRESS", "Investigation in Progress"), ("INVESTIGATION_SUBMITTED", "Investigation Submitted"), ("INVESTIGATION_APPROVED", "Investigation Approved"), ("INVESTIGATION_REJECTED", "Investigation Rejected"), ("ACTION_PLAN_IN_PROGRESS", "Action Plan in Progress"), ("ACTION_IMPLEMENTATION", "Action Implementation"), ("VERIFICATION", "Verification"), ("EFFECTIVENESS_REVIEW", "Effectiveness Review"), ("CLOSED", "Closed"), ("REOPENED", "Reopened"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=40)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("reopened_date", models.DateTimeField(blank=True, null=True)),
                ("closure_remarks", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("final_recommendations", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_capas", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_capas", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capas", to="organizations.department")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capas", to="organizations.location")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_capas", to=settings.AUTH_USER_MODEL)),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capas", to="organizations.plant")),
                ("reopened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reopened_capas", to=settings.AUTH_USER_MODEL)),
                ("source_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype")),
                ("sublocation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capas", to="organizations.sublocation")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_capas", to=settings.AUTH_USER_MODEL)),
                ("zone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capas", to="organizations.zone")),
            ],
            options={
                "verbose_name": "CAPA",
                "verbose_name_plural": "CAPAs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CAPAInvestigation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("investigation_date", models.DateField(blank=True, null=True)),
                ("investigation_team", models.TextField(blank=True)),
                ("investigation_method", models.CharField(choices=[("FIVE_WHY", "5 Why"), ("FISHBONE", "Fishbone / Ishikawa"), ("FAULT_TREE", "Fault Tree Analysis"), ("OTHER", "Other")], default="FIVE_WHY", max_length=20)),
                ("problem_statement", models.TextField(blank=True)),
                ("what_happened", models.TextField(blank=True)),
                ("impact_consequence", models.TextField(blank=True)),
                ("what_was_affected", models.TextField(blank=True)),
                ("sequence_of_events", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("evidence_collected", models.TextField(blank=True)),
                ("witness_statements", models.TextField(blank=True)),
                ("existing_controls", models.TextField(blank=True)),
                ("existing_control_in_place", models.BooleanField(default=False)),
                ("existing_control_followed", models.CharField(blank=True, max_length=20)),
                ("existing_control_adequate", models.CharField(blank=True, max_length=20)),
                ("control_failure_reason", models.TextField(blank=True)),
                ("control_gap_identified", models.TextField(blank=True)),
                ("why1", models.TextField(blank=True)),
                ("why2", models.TextField(blank=True)),
                ("why3", models.TextField(blank=True)),
                ("why4", models.TextField(blank=True)),
                ("why5", models.TextField(blank=True)),
                ("final_root_cause", models.TextField(blank=True)),
                ("root_cause_category", models.CharField(blank=True, choices=[("HUMAN_FACTOR", "Human Factor"), ("EQUIPMENT_FAILURE", "Equipment / Machine Failure"), ("MAINTENANCE", "Maintenance"), ("PROCEDURE_SOP", "Procedure / SOP"), ("TRAINING", "Training / Competency"), ("SUPERVISION", "Supervision"), ("DESIGN_ENGINEERING", "Design / Engineering"), ("MATERIAL", "Material"), ("PROCESS_METHOD", "Process / Method"), ("COMMUNICATION", "Communication"), ("RISK_ASSESSMENT", "Risk Assessment"), ("CONTRACTOR", "Contractor Management"), ("MANAGEMENT_SYSTEM", "Management System"), ("ENVIRONMENTAL", "Environmental Condition"), ("RESOURCE", "Resource / Availability"), ("COMPLIANCE", "Compliance"), ("OTHER", "Other")], max_length=40)),
                ("root_cause_details", models.TextField(blank=True)),
                ("contributing_factors", models.JSONField(blank=True, default=list)),
                ("extent_analysis", models.JSONField(blank=True, default=dict)),
                ("related_references", models.TextField(blank=True)),
                ("initial_likelihood", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("initial_severity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("initial_risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("existing_controls_summary", models.TextField(blank=True)),
                ("residual_likelihood", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("residual_severity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("residual_risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("risk_assessment_update_required", models.BooleanField(default=False)),
                ("risk_assessment_remarks", models.TextField(blank=True)),
                ("procedure_sop_revision_required", models.BooleanField(default=False)),
                ("training_required", models.BooleanField(default=False)),
                ("risk_assessment_revision_required", models.BooleanField(default=False)),
                ("engineering_modification_required", models.BooleanField(default=False)),
                ("moc_required", models.BooleanField(default=False)),
                ("legal_compliance_review_required", models.BooleanField(default=False)),
                ("document_control_update_required", models.BooleanField(default=False)),
                ("management_system_impact_details", models.TextField(blank=True)),
                ("investigation_conclusion", models.TextField(blank=True)),
                ("root_cause_confirmed", models.CharField(blank=True, max_length=20)),
                ("additional_investigation_required", models.BooleanField(default=False)),
                ("systemic_issue_identified", models.BooleanField(default=False)),
                ("extent_analysis_required", models.BooleanField(default=False)),
                ("action_plan_required", models.BooleanField(default=True)),
                ("investigator_recommendation", models.TextField(blank=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("affected_departments", models.ManyToManyField(blank=True, related_name="capa_investigations", to="organizations.department")),
                ("affected_locations", models.ManyToManyField(blank=True, related_name="capa_investigations", to="organizations.location")),
                ("affected_plants", models.ManyToManyField(blank=True, related_name="capa_investigations", to="organizations.plant")),
                ("capa", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="investigation", to="capa.capa")),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_capa_investigations", to=settings.AUTH_USER_MODEL)),
                ("lead_investigator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lead_capa_investigations", to=settings.AUTH_USER_MODEL)),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_capa_investigations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "CAPA Investigation",
                "verbose_name_plural": "CAPA Investigations",
            },
        ),
        migrations.CreateModel(
            name="CAPAAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_plan_type", models.CharField(choices=[("CORRECTION", "Correction"), ("CONTAINMENT", "Containment Action"), ("CORRECTIVE", "Corrective Action"), ("PREVENTIVE", "Preventive Action"), ("SYSTEM_IMPROVEMENT", "System Improvement"), ("TRAINING", "Training"), ("RISK_ASSESSMENT", "Risk Assessment"), ("PROCEDURE", "Procedure / SOP"), ("ENGINEERING", "Engineering Control"), ("INSPECTION", "Inspection / Monitoring"), ("COMPLIANCE", "Compliance"), ("MOC", "Management of Change"), ("COMMUNICATION", "Communication"), ("DOCUMENT_CONTROL", "Document Control")], max_length=40)),
                ("action_description", models.TextField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("URGENT", "Urgent")], default="MEDIUM", max_length=20)),
                ("control_type", models.CharField(blank=True, choices=[("ADMINISTRATIVE", "Administrative"), ("ENGINEERING", "Engineering"), ("BEHAVIORAL", "Behavioral"), ("ELIMINATION", "Elimination"), ("SUBSTITUTION", "Substitution"), ("PPE", "PPE"), ("OTHER", "Other")], max_length=20)),
                ("evidence_required", models.BooleanField(default=True)),
                ("verification_required", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("SUBMITTED", "Submitted"), ("REJECTED", "Rejected"), ("PENDING_VERIFICATION", "Pending Verification"), ("VERIFIED", "Verified"), ("CLOSED", "Closed"), ("OVERDUE", "Overdue")], db_index=True, default="PENDING", max_length=40)),
                ("source_action_object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_remarks", models.TextField(blank=True)),
                ("verified_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_action_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_source_action_items", to="contenttypes.contenttype")),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_capa_actions", to=settings.AUTH_USER_MODEL)),
                ("capa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="capa.capa")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_capa_actions", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_actions", to="organizations.department")),
            ],
            options={
                "ordering": ["target_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CAPAActionCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completion_date", models.DateField(default=django.utils.timezone.localdate)),
                ("completion_remarks", models.TextField(blank=True)),
                ("evidence", models.FileField(blank=True, null=True, upload_to="capa/action_completion/%Y/%m/")),
                ("submitted_for_verification", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="completion", to="capa.capaaction")),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_action_completions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CAPAActionVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("verification_method", models.CharField(blank=True, choices=[("PHYSICAL_INSPECTION", "Physical Inspection"), ("DOCUMENT_REVIEW", "Document Review"), ("PHOTO_VIDEO_REVIEW", "Photo / Video Review"), ("INTERVIEW", "Interview"), ("OBSERVATION", "Observation"), ("MEASUREMENT_TEST", "Measurement / Test"), ("SYSTEM_RECORD_REVIEW", "System Record Review"), ("OTHER", "Other")], max_length=40)),
                ("was_implemented", models.BooleanField(default=False)),
                ("matches_approved_action", models.BooleanField(default=False)),
                ("evidence_sufficient", models.BooleanField(default=False)),
                ("meets_required_standard", models.BooleanField(default=False)),
                ("verification_findings", models.TextField(blank=True)),
                ("deviation_deficiency", models.TextField(blank=True)),
                ("additional_evidence_required", models.BooleanField(default=False)),
                ("additional_evidence_remarks", models.TextField(blank=True)),
                ("result", models.CharField(choices=[("VERIFIED", "Verified / Accepted"), ("PARTIALLY_VERIFIED", "Partially Verified"), ("REJECTED", "Rejected")], default="VERIFIED", max_length=30)),
                ("rejection_reason", models.TextField(blank=True)),
                ("additional_action_required", models.TextField(blank=True)),
                ("reverification_required", models.BooleanField(default=False)),
                ("reverification_due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="verification", to="capa.capaaction")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_capa_actions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CAPAEffectivenessReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_date", models.DateField(blank=True, null=True)),
                ("corrective_working_as_intended", models.BooleanField(default=False)),
                ("preventive_working_as_intended", models.BooleanField(default=False)),
                ("risk_reduced_as_expected", models.BooleanField(default=False)),
                ("controls_adequate", models.BooleanField(default=False)),
                ("systemic_cause_addressed", models.BooleanField(default=False)),
                ("effectiveness_evidence", models.TextField(blank=True)),
                ("evidence_description", models.TextField(blank=True)),
                ("review_findings", models.TextField(blank=True)),
                ("observed_improvement", models.TextField(blank=True)),
                ("remaining_risk_gap", models.TextField(blank=True)),
                ("result", models.CharField(choices=[("EFFECTIVE", "Effective"), ("PARTIALLY_EFFECTIVE", "Partially Effective"), ("NOT_EFFECTIVE", "Not Effective")], default="EFFECTIVE", max_length=30)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("capa", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="effectiveness_review", to="capa.capa")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="effectiveness_reviews", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CAPAAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="capa/attachments/%Y/%m/")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="capa.capaaction")),
                ("capa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="capa.capa")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_capa_attachments", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CAPAComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_comments", to=settings.AUTH_USER_MODEL)),
                ("capa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="capa.capa")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CAPAApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approval_type", models.CharField(choices=[("INVESTIGATION", "Investigation"), ("CLOSURE", "Closure")], max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_approvals", to=settings.AUTH_USER_MODEL)),
                ("capa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="capa.capa")),
            ],
            options={"ordering": ["-approved_at", "-id"]},
        ),
        migrations.CreateModel(
            name="CAPAAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=80)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("capa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="capa.capa")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capa_audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-timestamp", "-id"]},
        ),
    ]
