# Generated by Django 5.2.14 on 2026-09-01 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['status'], name='capa_capa_status_04b7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['source_type'], name='capa_capa_source__c9a937_idx'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['plant', 'status'], name='capa_capa_plant_i_e62dc0_idx'),
        ),
    ]
